### ISSUE TITLE
Step 1: Delineate urban greenspaces

### ISSUE THREAD

**Issue by coreytcallaghan** [coreytcallaghan/urban_greenspaces#1]
Currently working on this, and have a volunteer willing to help.

I am using this cool tool to do it: http://geojson.io/#map=2/20.0/0.0

**Comment by johnWilshire** [comment]
Is there a repo for this?, where should I put the .geojson files I create

I just made one for [Shinjuku Gyo-en](https://en.wikipedia.org/wiki/Shinjuku_Gyo-en)!

**Comment by coreytcallaghan** [comment]
I just have a folder there for now. Eventually will split this one folder out into its own repo.
