### ISSUE TITLE
Step 2: Convert eBird to a format which can be easily spatially queried

### ISSUE THREAD

**Issue by coreytcallaghan** [coreytcallaghan/urban_greenspaces#2]
The object here is to be able to easily convert the eBird dataset for a format which can be easily spatially queried. In that, for a given delineated greenspace, we can easily extract all data for that greenspace.

The current working theory is that a sql database might be the best way to do this.

**Comment by coreytcallaghan** [comment]
[Here is a link to the raw eBird data](https://cloudstor.aarnet.edu.au/sender/?s=download&token=58cbc57b-b92b-1934-1a50-3cf0d9555012) in the format in which it is currently downloaded. Only for Australia at the moment.

Need to figure out how to get this into a format to spatially query it.

**Comment by coreytcallaghan** [comment]
Not exactly sure what [this link](http://www.diva-portal.org/smash/get/diva2:706189/FULLTEXT01.pdf) is yet, but it has some nice code we can use for MySQL import, I think.

**Comment by johnWilshire** [comment]
I think we will need to convert the geojsons to wkt format to query the db: we can do this via this [tool](https://github.com/mapbox/wellknown), or a similar python tool.

I also think we definitely want to set it up using a [spatial index](https://dev.mysql.com/doc/refman/5.7/en/using-spatial-indexes.html)

**Comment by johnWilshire** [comment]
Or probably the easiest way would be via the [wellknown](https://cran.r-project.org/web/packages/wellknown/vignettes/wellknown_vignette.html) package in R
